# Generated by Django 3.2.2 on 2023-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
