# Generated by Django 3.2.2 on 2023-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20230319_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('null', 'Null'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
