# Generated by Django 3.2.2 on 2023-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20230320_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, choices=[('kilo', 'kilo'), ('gram', 'gram'), ('kilogram', 'kilogram'), ('piece', 'piece'), ('crate', 'crate'), ('roll', 'roll'), ('cup', 'cup'), ('can', 'can'), ('bottle', 'bottle'), ('paint', 'paint'), ('sack', 'sack'), ('bag', 'bag'), ('package', 'package'), ('basket', 'basket'), ('bucket', 'bucket'), ('truck', 'truck')], max_length=20, null=True),
        ),
    ]
